// Auto-generated by DevSure for module: Auth

// This file is regenerated when tests are executed inside sandbox.


const sandboxModule = require("./sample");
const sample = sandboxModule;

const { register } = sandboxModule;

const authService = sandboxModule.authService;
const generateToken = sandboxModule.generateToken;

// Aliases for AI-generated tests that may use service/controller/module style calls.
const service = sandboxModule;
const controller = sandboxModule;
const moduleUnderTest = sandboxModule;
const auth = sandboxModule;
const authController = sandboxModule;
const authModule = sandboxModule;



function createMockResponse() {
  return {
    status: jest.fn().mockReturnThis(),
    json: jest.fn().mockReturnThis(),
    send: jest.fn().mockReturnThis(),
    end: jest.fn().mockReturnThis()
  };
}

function createMockRequest(overrides = {}) {
  return {
    body: {},
    params: {},
    query: {},
    headers: {},
    user: {
      _id: "user123",
      id: "user123",
      role: "user"
    },
    ...overrides
  };
}


// Function: register
test('should register a new user successfully', async () => {
  jest.restoreAllMocks();
  const user = { _id: 'user-1', fullName: 'John Doe', email: 'john@example.com', role: 'user', createdAt: '2025-01-01T00:00:00.000Z' };
  jest.spyOn(authService, 'registerUser').mockResolvedValue(user);
  const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com', password: 'secret123', role: 'user' } });
  const res = createMockResponse();
  await register(req, res);
  expect(res.status).toHaveBeenCalledWith(201);
  expect(res.json).toHaveBeenCalledWith({
    success: true,
    message: 'User registered successfully',
    data: {
      user: { id: 'user-1', fullName: 'John Doe', email: 'john@example.com', role: 'user', createdAt: '2025-01-01T00:00:00.000Z' },
      token: expect.any(String)
    }
  });
});

test('should call authService.registerUser with provided registration details', async () => {
  jest.restoreAllMocks();
  const user = { _id: 'user-1', fullName: 'John Doe', email: 'john@example.com', role: 'user', createdAt: '2025-01-01T00:00:00.000Z' };
  const spy = jest.spyOn(authService, 'registerUser').mockResolvedValue(user);
  const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com', password: 'secret123', role: 'user' } });
  const res = createMockResponse();
  await register(req, res);
  expect(spy).toHaveBeenCalledTimes(1);
  expect(spy).toHaveBeenCalledWith({ fullName: 'John Doe', email: 'john@example.com', password: 'secret123', role: 'user' });
});

test('should return user data without password in success response', async () => {
  jest.restoreAllMocks();
  const user = { _id: 'user-1', fullName: 'John Doe', email: 'john@example.com', role: 'user', createdAt: '2025-01-01T00:00:00.000Z', password: 'secret123' };
  jest.spyOn(authService, 'registerUser').mockResolvedValue(user);
  const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com', password: 'secret123', role: 'user' } });
  const res = createMockResponse();
  await register(req, res);
  const payload = res.json.mock.calls[0][0];
  expect(payload.data.user).toEqual({ id: 'user-1', fullName: 'John Doe', email: 'john@example.com', role: 'user', createdAt: '2025-01-01T00:00:00.000Z' });
  expect(payload.data.user.password).toBeUndefined();
});

test('should reject registration when full name is missing', async () => {
  jest.restoreAllMocks();
  const req = createMockRequest({ body: { email: 'john@example.com', password: 'secret123' } });
  const res = createMockResponse();
  await register(req, res);
  expect(res.status).toHaveBeenCalledWith(400);
  expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' });
});

test('should reject registration when email is missing', async () => {
  jest.restoreAllMocks();
  const req = createMockRequest({ body: { fullName: 'John Doe', password: 'secret123' } });
  const res = createMockResponse();
  await register(req, res);
  expect(res.status).toHaveBeenCalledWith(400);
  expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' });
});

test('should reject registration when password is missing', async () => {
  jest.restoreAllMocks();
  const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com' } });
  const res = createMockResponse();
  await register(req, res);
  expect(res.status).toHaveBeenCalledWith(400);
  expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' });
});

test('should reject registration when full name is empty string', async () => {
  jest.restoreAllMocks();
  const req = createMockRequest({ body: { fullName: '', email: 'john@example.com', password: 'secret123' } });
  const res = createMockResponse();
  await register(req, res);
  expect(res.status).toHaveBeenCalledWith(400);
  expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' });
});

test('should handle registration service failure', async () => {
  jest.restoreAllMocks();
  jest.spyOn(authService, 'registerUser').mockRejectedValue(new Error('Email already exists'));
  const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com', password: 'secret123', role: 'user' } });
  const res = createMockResponse();
  await register(req, res);
  expect(res.status).toHaveBeenCalledWith(400);
  expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Email already exists' });
});

test('should not call authService when required fields are missing', async () => {
  jest.restoreAllMocks();
  const spy = jest.spyOn(authService, 'registerUser');
  const req = createMockRequest({ body: { email: 'john@example.com', password: 'secret123' } });
  const res = createMockResponse();
  await register(req, res);
  expect(res.status).toHaveBeenCalledWith(400);
  expect(spy).not.toHaveBeenCalled();
});