// Auto-generated by DevSure for module: Auth

// This file is regenerated when tests are executed inside sandbox.


const sandboxModule = require("./sample");
const sample = sandboxModule;

const { register, login, profile } = sandboxModule;

const authService = sandboxModule.authService;
const generateToken = sandboxModule.generateToken;

// Aliases for AI-generated tests that may use service/controller/module style calls.
const service = sandboxModule;
const controller = sandboxModule;
const moduleUnderTest = sandboxModule;
const auth = sandboxModule;
const authController = sandboxModule;
const authModule = sandboxModule;



function createMockResponse() {
  return {
    status: jest.fn().mockReturnThis(),
    json: jest.fn().mockReturnThis(),
    send: jest.fn().mockReturnThis(),
    end: jest.fn().mockReturnThis()
  };
}

function createMockRequest(overrides = {}) {
  return {
    body: {},
    params: {},
    query: {},
    headers: {},
    user: {
      _id: "user123",
      id: "user123",
      role: "user"
    },
    ...overrides
  };
}


// Function: register
test('should register a user successfully with all provided details', async () => { jest.clearAllMocks(); const user = { _id: 'user_123', fullName: 'John Doe', email: 'john@example.com', password: 'hashed', role: 'attendee', createdAt: '2024-01-01T00:00:00.000Z' }; authService.registerUser.mockResolvedValue(user); generateToken.mockReturnValue('jwt-token'); const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com', password: 'secret123', role: 'attendee' } }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(201); expect(res.json).toHaveBeenCalledWith(expect.objectContaining({ success: true, message: 'User registered successfully', data: expect.objectContaining({ user: expect.objectContaining({ id: 'user_123', fullName: 'John Doe', email: 'john@example.com', role: 'attendee', createdAt: '2024-01-01T00:00:00.000Z' }), token: 'jwt-token' }) })); expect(authService.registerUser).toHaveBeenCalledWith({ fullName: 'John Doe', email: 'john@example.com', password: 'secret123', role: 'attendee' }); expect(generateToken).toHaveBeenCalledWith(user); const responsePayload = res.json.mock.calls[0][0]; expect(responsePayload.data.user).not.toHaveProperty('password'); expect(responsePayload.data.user).not.toHaveProperty('passwordHash'); });

test('should register a user successfully without an optional role', async () => { jest.clearAllMocks(); const user = { _id: 'user_456', fullName: 'Jane Doe', email: 'jane@example.com', role: 'attendee', createdAt: '2024-02-01T00:00:00.000Z' }; authService.registerUser.mockResolvedValue(user); generateToken.mockReturnValue('jwt-token-2'); const req = createMockRequest({ body: { fullName: 'Jane Doe', email: 'jane@example.com', password: 'secret456' } }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(201); expect(res.json).toHaveBeenCalledWith(expect.objectContaining({ success: true, message: 'User registered successfully', data: expect.objectContaining({ user: expect.objectContaining({ id: 'user_456', fullName: 'Jane Doe', email: 'jane@example.com', role: 'attendee', createdAt: '2024-02-01T00:00:00.000Z' }), token: 'jwt-token-2' }) })); expect(authService.registerUser).toHaveBeenCalledWith(expect.objectContaining({ fullName: 'Jane Doe', email: 'jane@example.com', password: 'secret456' })); expect(generateToken).toHaveBeenCalledWith(user); });

test('should return 400 when fullName is missing', async () => { jest.clearAllMocks(); const req = createMockRequest({ body: { email: 'john@example.com', password: 'secret123' } }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' }); expect(authService.registerUser).not.toHaveBeenCalled(); expect(generateToken).not.toHaveBeenCalled(); });

test('should return 400 when email is missing', async () => { jest.clearAllMocks(); const req = createMockRequest({ body: { fullName: 'John Doe', password: 'secret123' } }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' }); expect(authService.registerUser).not.toHaveBeenCalled(); expect(generateToken).not.toHaveBeenCalled(); });

test('should return 400 when password is missing', async () => { jest.clearAllMocks(); const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com' } }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' }); expect(authService.registerUser).not.toHaveBeenCalled(); expect(generateToken).not.toHaveBeenCalled(); });

test('should return 400 when all required fields are missing', async () => { jest.clearAllMocks(); const req = createMockRequest({ body: {} }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' }); expect(authService.registerUser).not.toHaveBeenCalled(); expect(generateToken).not.toHaveBeenCalled(); });

test('should return 400 when fullName is an empty string', async () => { jest.clearAllMocks(); const req = createMockRequest({ body: { fullName: '', email: 'john@example.com', password: 'secret123' } }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Full name, email, and password are required' }); expect(authService.registerUser).not.toHaveBeenCalled(); expect(generateToken).not.toHaveBeenCalled(); });

test('should return 400 when authService.registerUser throws Email already exists', async () => { jest.clearAllMocks(); authService.registerUser.mockRejectedValue(new Error('Email already exists')); const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com', password: 'secret123' } }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Email already exists' }); expect(generateToken).not.toHaveBeenCalled(); });

test('should return 400 when authService.registerUser throws User validation failed', async () => { jest.clearAllMocks(); authService.registerUser.mockRejectedValue(new Error('User validation failed')); const req = createMockRequest({ body: { fullName: 'John Doe', email: 'john@example.com', password: 'secret123' } }); const res = createMockResponse(); await register(req, res); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'User validation failed' }); expect(generateToken).not.toHaveBeenCalled(); });

// Function: login
test('logs in successfully with valid credentials', async () => { jest.clearAllMocks(); const req = createMockRequest({ email: 'john@example.com', password: 'secret123' }); const res = createMockResponse(); const user = { _id: 'user_123', fullName: 'John Doe', email: 'john@example.com', role: 'attendee', createdAt: '2024-01-01T00:00:00.000Z' }; authService.loginUser.mockResolvedValue(user); generateToken.mockReturnValue('jwt-token'); await login(req, res); expect(authService.loginUser).toHaveBeenCalledWith({ email: 'john@example.com', password: 'secret123' }); expect(generateToken).toHaveBeenCalledWith(user); expect(res.status).toHaveBeenCalledWith(200); expect(res.json).toHaveBeenCalledWith({ success: true, message: 'Login successful', data: { user: { id: user._id, fullName: user.fullName, email: user.email, role: user.role, createdAt: user.createdAt }, token: 'jwt-token' } }); })

test('rejects login when email is missing', async () => { jest.clearAllMocks(); const req = createMockRequest({ password: 'secret123' }); const res = createMockResponse(); await login(req, res); expect(authService.loginUser).not.toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Email and password are required' }); })

test('rejects login when password is missing', async () => { jest.clearAllMocks(); const req = createMockRequest({ email: 'john@example.com' }); const res = createMockResponse(); await login(req, res); expect(authService.loginUser).not.toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Email and password are required' }); })

test('rejects login when email and password are both missing', async () => { jest.clearAllMocks(); const req = createMockRequest({}); const res = createMockResponse(); await login(req, res); expect(authService.loginUser).not.toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(400); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Email and password are required' }); })

test('returns 401 when loginUser throws Invalid credentials', async () => { jest.clearAllMocks(); authService.loginUser.mockRejectedValue(new Error('Invalid credentials')); const req = createMockRequest({ email: 'john@example.com', password: 'wrongpassword' }); const res = createMockResponse(); await login(req, res); expect(authService.loginUser).toHaveBeenCalledWith({ email: 'john@example.com', password: 'wrongpassword' }); expect(generateToken).not.toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(401); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Invalid credentials' }); })

test('returns 401 when loginUser throws User not found', async () => { jest.clearAllMocks(); authService.loginUser.mockRejectedValue(new Error('User not found')); const req = createMockRequest({ email: 'john@example.com', password: 'secret123' }); const res = createMockResponse(); await login(req, res); expect(authService.loginUser).toHaveBeenCalledWith({ email: 'john@example.com', password: 'secret123' }); expect(generateToken).not.toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(401); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'User not found' }); })

test('returns 401 when loginUser throws Wrong password', async () => { jest.clearAllMocks(); authService.loginUser.mockRejectedValue(new Error('Wrong password')); const req = createMockRequest({ email: 'john@example.com', password: 'badpassword' }); const res = createMockResponse(); await login(req, res); expect(authService.loginUser).toHaveBeenCalledWith({ email: 'john@example.com', password: 'badpassword' }); expect(generateToken).not.toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(401); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Wrong password' }); })

test('does not expose password fields in success response', async () => { jest.clearAllMocks(); const req = createMockRequest({ email: 'john@example.com', password: 'secret123' }); const res = createMockResponse(); const user = { _id: 'user_123', fullName: 'John Doe', email: 'john@example.com', role: 'attendee', createdAt: '2024-01-01T00:00:00.000Z', password: 'secret123', passwordHash: 'hash' }; authService.loginUser.mockResolvedValue(user); generateToken.mockReturnValue('jwt-token'); await login(req, res); expect(res.status).toHaveBeenCalledWith(200); const responseBody = res.json.mock.calls[0][0]; expect(responseBody.data.user).not.toHaveProperty('password'); expect(responseBody.data.user).not.toHaveProperty('passwordHash'); })

test('calls generateToken with the user object returned by loginUser', async () => { jest.clearAllMocks(); const req = createMockRequest({ email: 'john@example.com', password: 'secret123' }); const res = createMockResponse(); const user = { _id: 'user_123', fullName: 'John Doe', email: 'john@example.com', role: 'attendee', createdAt: '2024-01-01T00:00:00.000Z' }; authService.loginUser.mockResolvedValue(user); generateToken.mockReturnValue('jwt-token'); await login(req, res); expect(generateToken).toHaveBeenCalledTimes(1); expect(generateToken).toHaveBeenCalledWith(user); })

test('returns all required user fields and token in success response', async () => { jest.clearAllMocks(); const req = createMockRequest({ email: 'john@example.com', password: 'secret123' }); const res = createMockResponse(); const user = { _id: 'user_123', fullName: 'John Doe', email: 'john@example.com', role: 'attendee', createdAt: '2024-01-01T00:00:00.000Z' }; authService.loginUser.mockResolvedValue(user); generateToken.mockReturnValue('jwt-token'); await login(req, res); const responseBody = res.json.mock.calls[0][0]; expect(responseBody.success).toBe(true); expect(responseBody.message).toBe('Login successful'); expect(responseBody.data.user).toEqual({ id: user._id, fullName: user.fullName, email: user.email, role: user.role, createdAt: user.createdAt }); expect(responseBody.data.token).toBe('jwt-token'); })

// Function: profile
test('should return 200 and user data when authService.getProfile resolves', async () => { const user = { id: 'user_123', fullName: 'John Doe', email: 'john@example.com' }; const req = createMockRequest(); req.user = { _id: 'user_123' }; const res = createMockResponse(); authService.getProfile = jest.fn().mockResolvedValue(user); await profile(req, res); expect(authService.getProfile).toHaveBeenCalledWith('user_123'); expect(res.status).toHaveBeenCalledWith(200); expect(res.json).toHaveBeenCalledWith({ success: true, data: user }); })

test('should pass req.user._id to authService.getProfile', async () => { const req = createMockRequest(); req.user = { _id: 'user_456' }; const res = createMockResponse(); authService.getProfile = jest.fn().mockResolvedValue({ id: 'user_456' }); await profile(req, res); expect(authService.getProfile).toHaveBeenCalledWith('user_456'); })

test('should return 500 and success false when authService.getProfile rejects', async () => { const req = createMockRequest(); req.user = { _id: 'user_123' }; const res = createMockResponse(); authService.getProfile = jest.fn().mockRejectedValue(new Error('Profile not found')); await profile(req, res); expect(res.status).toHaveBeenCalledWith(500); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Profile not found' }); })

test('should preserve a generic service error message in the 500 response', async () => { const req = createMockRequest(); req.user = { _id: 'user_123' }; const res = createMockResponse(); authService.getProfile = jest.fn().mockRejectedValue(new Error('Database unavailable')); await profile(req, res); expect(res.status).toHaveBeenCalledWith(500); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'Database unavailable' }); })

test('should return 500 and not call getProfile when req.user is missing', async () => { const req = createMockRequest(); const res = createMockResponse(); authService.getProfile = jest.fn(); await profile(req, res); expect(authService.getProfile).not.toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(500); expect(res.json).toHaveBeenCalledWith({ success: false, message: expect.any(String) }); })

test('should return 500 and not call getProfile when req.user is null', async () => { const req = createMockRequest(); req.user = null; const res = createMockResponse(); authService.getProfile = jest.fn(); await profile(req, res); expect(authService.getProfile).not.toHaveBeenCalled(); expect(res.status).toHaveBeenCalledWith(500); expect(res.json).toHaveBeenCalledWith({ success: false, message: expect.any(String) }); })

test('should return 200 with null data when getProfile resolves to null', async () => { const req = createMockRequest(); req.user = { _id: 'user_123' }; const res = createMockResponse(); authService.getProfile = jest.fn().mockResolvedValue(null); await profile(req, res); expect(res.status).toHaveBeenCalledWith(200); expect(res.json).toHaveBeenCalledWith({ success: true, data: null }); })

test('should include the full user object returned by getProfile in the response body', async () => { const user = { id: 'user_123', fullName: 'Jane Doe', email: 'jane@example.com', role: 'attendee', createdAt: '2024-01-01T00:00:00.000Z' }; const req = createMockRequest(); req.user = { _id: 'user_123' }; const res = createMockResponse(); authService.getProfile = jest.fn().mockResolvedValue(user); await profile(req, res); expect(res.json).toHaveBeenCalledWith({ success: true, data: expect.objectContaining({ id: 'user_123', fullName: 'Jane Doe', email: 'jane@example.com', role: 'attendee', createdAt: '2024-01-01T00:00:00.000Z' }) }); })

test('should not let a rejected profile request escape as an unhandled promise rejection', async () => { const req = createMockRequest(); req.user = { _id: 'user_123' }; const res = createMockResponse(); authService.getProfile = jest.fn().mockRejectedValue(new Error('boom')); await expect(profile(req, res)).resolves.toBeUndefined(); expect(res.status).toHaveBeenCalledWith(500); expect(res.json).toHaveBeenCalledWith({ success: false, message: 'boom' }); })